CREATE TABLE IF NOT EXISTS Global_Economy (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL UNIQUE,
    user_name TEXT NOT NULL,
    balance REAL NOT NULL DEFAULT 0.0,
    bonus INTEGER NOT NULL DEFAULT 0,
    num_bets INTEGER NOT NULL DEFAULT 0,
    num_wins INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Betting_Pool (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id INTEGER NOT NULL,
    game_type INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    team TEXT NOT NULL,
    wager REAL NOT NULL DEFAULT 0.0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Global_Economy(user_id)
);

CREATE TABLE IF NOT EXISTS Bet_History (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id INTEGER NOT NULL,
    game_type INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    team TEXT NOT NULL,
    wager REAL,
    payout REAL,
    moneyline_win BOOLEAN,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Global_Economy(user_id)
);

CREATE TABLE IF NOT EXISTS Current_Games (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id INTEGER NOT NULL,
    away_team TEXT NOT NULL,
    home_team TEXT NOT NULL,
    game_type INTEGER NOT NULL,
    start_date DATE NOT NULL,
    start_time TIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);